### ISSUE TITLE
Big Idea 1 Feedback - Nach Mohan : 1/28/18

### ISSUE THREAD

**Issue by Nach-Mohan** [w201rdada/portfolio-omsteadily#2]
**Gist**: More accurate calculation of effort expended in a workout based on individualized metrics.

**Keep**: The problem statement is specified clearly and showcases the technical strength that you have in this area.

**Cut**: The length of the idea exceeds the word limit specified for the project. Second and third paragraph in the introduction and the identification of bar bells and plates can be made more concise.

**Re-arrange**: The challenges specified in the middle section will be more appropriate if moved to the end section.

**Add**: Add more details on how image recognition will help to overcome the challenges.

**General comments**: The idea of individual recognition stated in the end section is interesting, but will be helpful if basic information on how this can be implemented is specified in the middle section.

**Comment by omsteadily** [comment]
Thanks, Nach.  You're right that it is too long-winded.  I'm working on cutting it down.
