### ISSUE TITLE
Big Idea 1 Feedback - Adam Yang

### ISSUE THREAD

**Issue by adamcy99** [w201rdada/portfolio-omsteadily#3]
**Gist**: From your introduction I thought this idea would be applied to in a competitive event but after reading your conclusion, I now understand it's a system set up in a gym to automate all the calculations while each person does the workout. I think it would be good to mention that more clearly in the introduction.
**Keep**: I really like the general idea, using basic physics to calculate how much work (F*d) is being done by each person at the gym. 
**Cut**: You expressed your idea very clearly with maybe too many reiterations. I get the feeling you're writing down all your thoughts  and then will go back and cut it down a bit. I think there is a word limit to this assignment but I'm not sure how strict that is. I think too much emphasis is being put on image recognition for determining what weight is being used when a simple alternative is to maybe have a scale at each station, or let the person manually enter it in when he starts working out at a station. 
**Re-arrange**: I think your idea is very good, but I picture it a little differently. Maybe instead of having cameras placed around the gym, just have them next to each station. For example, a dead-lift station can have a camera next to the lift area pointing to the lifter's mid drift, from the side. That way, it's much easier to use image recognition to determine the distance being lifted. Also, the lifter can input the weight he wants to lift on a console that the camera is built into. Or he can input the weight via an app that connects to each of these camera set ups so he can have a record of the "Work" he's done.
**Add**: I think you thought about this a lot. I wouldn't add anything but maybe tweak your idea a bit.
**Other Comments**: I think using image recognition to keep track of the distance the weight is traveling during certain exercises is a good idea. However, I'm not sure how necessary it would be for the weight itself. By cutting the weight image recognition part, you can focus on the distance image recognition and shorten your write-up. You might be able to mention in an aside that image recognition can be applied to measuring the weight being lifted but I don't think you need to go into too much detail about the variables.

**Comment by omsteadily** [comment]
Thanks, Adam.  You're right that it was fairly stream-of-consciousness, and per your advice I've decided to clarify the target client in the first part - focusing on CrossFit rather than gyms.  I'm reluctant to go the route of a hardware shortcut (ie, scales), as that would represent a sizable capital expense, and would make the idea less scalable (also more easily copied).
